# Sources officielles de financement pour Linux Mint

patreon: linuxmint
custom:
  - https://www.linuxmint.com/donors.php
  - https://www.linuxmint.com/donate.php
  - https://www.linuxmint.com/cryptocurrencies.php
