# ================================
# LMEE - Applications Configuration
# ================================

APPS_DEV=(
  "git"
  "build-essential"
  "curl"
  "nodejs"
  "npm"
)

APPS_SYSADMIN=(
  "htop"
  "iftop"
  "nmap"
  "net-tools"
  "lsof"
)

APPS_NETWORK=(
  "wireshark"
  "tcpdump"
  "traceroute"
)

APPS_ENGINEERING=(
  "gparted"
  "virtualbox"
  "docker.io"
  "docker-compose"
)
