# ================================
# LMEE - Developer Configuration
# ================================

INSTALL_IDES=true
IDES=("vscode" "vim")

INSTALL_LANGUAGES=true
LANGUAGES=("python3" "golang" "rustc")
