# ================================
# LMEE - Modules Configuration
# ================================

# FULL++ preset (tout)
PRESET_full=(
  "shell/zsh.sh"
  "dev/dev-tools.sh"
  "sysadmin/sysadmin-tools.sh"
  "network/network-tools.sh"
  "security/hardening.sh"
  "system/optimizations.sh"
  "apps/engineering-suite.sh"
)

# Minimal preset
PRESET_minimal=(
  "shell/zsh.sh"
)

# Developer preset
PRESET_dev=(
  "shell/zsh.sh"
  "dev/dev-tools.sh"
)

# Sysadmin preset
PRESET_sysadmin=(
  "shell/zsh.sh"
  "sysadmin/sysadmin-tools.sh"
)

# Network preset
PRESET_network=(
  "shell/zsh.sh"
  "network/network-tools.sh"
)
