# ================================
# LMEE - Network Configuration
# ================================

SET_DNS=true
DNS_SERVERS=("1.1.1.1" "8.8.8.8")

INSTALL_NETWORK_TOOLS=true
ENABLE_IPV6_TWEAKS=false
