# ================================
# LMEE - Global Options
# ================================

# Mode simulation (ne fait qu'afficher les modules)
DRY_RUN=false

# Mode verbeux
VERBOSE=true

# Couleurs terminal
COLOR_SUCCESS="\e[32m"
COLOR_ERROR="\e[31m"
COLOR_INFO="\e[34m"
COLOR_RESET="\e[0m"
