# ================================
# LMEE - Sysadmin Configuration
# ================================

INSTALL_MONITORING_TOOLS=true
MONITORING_TOOLS=("htop" "glances" "bmon")

INSTALL_BACKUP_TOOLS=true
BACKUP_TOOLS=("rsync" "borgbackup")
