# ================================
# LMEE - System Configuration
# ================================

ENABLE_SWAP_TUNING=true
ENABLE_CPU_TWEAKS=true
ENABLE_IO_SCHEDULER_OPTIMIZATION=true
ENABLE_BOOT_CLEANUP=true
ENABLE_AUTOREMOVE=true
ENABLE_FLATPAK_SETUP=true
